module.exports = [
    {competitorNumber: "A100", firstName: "George", lastName: "Washington", },
    {competitorNumber: "A101", firstName: "John", lastName: "Adams", },
    {competitorNumber: "A102", firstName: "Thomas", lastName: "Jefferson", },
    {competitorNumber: "A103", firstName: "James", lastName: "Madison", },
    {competitorNumber: "A104", firstName: "James", lastName: "Monroe", },
    {competitorNumber: "J100", teamName: "Virginia 1", groupNames: "George Washington - Thomas Jefferson - James Madison - James Monroe"},
    {competitorNumber: "J101", teamName: "Massachusetts 1", groupNames: "John Adams - John Quincy Adams - John F Kennedy - George H W Bush"},
    {competitorNumber: "J102", teamName: "Carolina 1", groupNames: "Andrew Jackson - James K Polk - Andrew Johnson"},
    {competitorNumber: "J103", teamName: "Virginia 2", groupNames: "William Henry Harrison - Zachary Taylor - John Tyler"},
    {competitorNumber: "J104", teamName: "Pennsylvania 1", groupNames: "James Buchanan - Jonathon Doe"},
    {competitorNumber: "A110", firstName: "John Quincy", lastName: "Adams", },
    {competitorNumber: "A111", firstName: "Andrew", lastName: "Jackson", },
    {competitorNumber: "A112", firstName: "Martin", lastName: "Van Buren", },
    {competitorNumber: "A113", firstName: "William Henry", lastName: "Harrison", },
    {competitorNumber: "A114", firstName: "John", lastName: "Tyler", },
    {competitorNumber: "J110", teamName: "New York 1", groupNames: "Millard Fillmore - Theodore Roosevelt - Franklin D Roosevelt"},
    {competitorNumber: "J111", teamName: "Ohio 1", groupNames: "Ulysses S Grant - Rutherford B Hayes - James A Garfield"},
    {competitorNumber: "J112", teamName: "Ohio 2", groupNames: "Benjamin Harrison - William McKinley - William Howard Taft"},
    {competitorNumber: "J113", teamName: "Midwest 1", groupNames: "Herbert Hoover - Harry S Truman - Warren G Harding"},
    {competitorNumber: "J114", teamName: "Texas 1", groupNames: "Dwight D Eisenhower - Lyndon B Johnson"},
    {competitorNumber: "A120", firstName: "James K", lastName: "Polk", },
    {competitorNumber: "A121", firstName: "Zachary", lastName: "Taylor", },
    {competitorNumber: "A122", firstName: "Millard", lastName: "Fillmore", },
    {competitorNumber: "A123", firstName: "Franklin", lastName: "Pierce", },
    {competitorNumber: "A124", firstName: "James", lastName: "Buchanan", },
    {competitorNumber: "A130", firstName: "Abraham", lastName: "Lincoln", },
    {competitorNumber: "A131", firstName: "Andrew", lastName: "Johnson", },
    {competitorNumber: "A132", firstName: "Ulysses S", lastName: "Grant", },
    {competitorNumber: "A133", firstName: "Rutherford Birchard", lastName: "Hayes", },
    {competitorNumber: "A134", firstName: "James A", lastName: "Garfield", },
    {competitorNumber: "J120", teamName: "Midwest 2", groupNames: "Jim McMahon - Walter Payton - Willie Gault"},
    {competitorNumber: "J121", teamName: "Denver 1", groupNames: "John Elway - Tony Dorsett - Ricky Nattiel"},
    {competitorNumber: "J122", teamName: "Ohio 3 1", groupNames: "Bernie Kosar - Kevin Mack - Reggie Langhorne"},
    {competitorNumber: "J123", teamName: "Texas 2", groupNames: "Danny White - Herschel Walker - Mike Renfro"},
    {competitorNumber: "J124", teamName: "Miami 1", groupNames: "Dan Marino - Lorenzo Hampton - Mark Duper"},
    {competitorNumber: "A140", firstName: "Chester A", lastName: "Arthur", },
    {competitorNumber: "A141", firstName: "Grover", lastName: "Cleveland", },
    {competitorNumber: "A142", firstName: "Benjamin", lastName: "Harrison", },
    {competitorNumber: "A143", firstName: "Grover", lastName: "Cleveland", },
    {competitorNumber: "A144", firstName: "William", lastName: "McKinley", },
    {competitorNumber: "A150", firstName: "Theodore", lastName: "Roosevelt", },
    {competitorNumber: "A151", firstName: "William H", lastName: "Taft", },
    {competitorNumber: "A152", firstName: "Woodrow", lastName: "Wilson", },
    {competitorNumber: "A153", firstName: "Warren G", lastName: "Harding", },
    {competitorNumber: "A154", firstName: "Calvin", lastName: "Coolidge", },
];